In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [9]:
a.shape

(5,)

In [10]:
b = [[1,2,3],[4,5,6]]

In [11]:
b = np.array(b)

In [12]:
b.shape

(2, 3)

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
a = np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [31]:
a.shape

(30,)

In [32]:
a.reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
b = a.reshape((5,2,3))

In [37]:
b.shape

(5, 2, 3)

In [41]:
a.reshape((5,2,-1))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [42]:
np.sum(b)

435

In [48]:
np.sum(b, axis=2)

array([[ 3, 12],
       [21, 30],
       [39, 48],
       [57, 66],
       [75, 84]])

In [49]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [50]:
b[0,0,0]

0

In [52]:
b[3,0,1]

19

In [53]:
b[1,1]

array([ 9, 10, 11])

In [54]:
b[:,0,0]

array([ 0,  6, 12, 18, 24])

In [61]:
b[:3,0,0]

array([ 0,  6, 12])

In [66]:
b[1:3,:,2]

array([[ 8, 11],
       [14, 17]])